os: linux
sudo: required
language: cpp
compiler: gcc

before_install:
  - uname -a
  - git submodule update --init --recursive

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - cmake
    - protobuf-compiler 
    - libboost-dev 
    - libgoogle-glog-dev 
    - libgflags-dev
    - libprotobuf-dev 
    - libncurses5-dev 
    - libsodium-dev 

branches:
  only:
    - master
      
script:
  - mkdir build
  - cd build
  - cmake ../ -DBUILD_TEST=1 && make

