os: linux
dist: trusty
sudo: required
language: cpp
compiler: gcc

before_install:
  - uname -a
  - git submodule update --init --recursive

  - sudo add-apt-repository ppa:chris-lea/libsodium;
  - sudo echo "deb http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list;
  - sudo echo "deb-src http://ppa.launchpad.net/chris-lea/libsodium/ubuntu trusty main" >> /etc/apt/sources.list;
  - sudo apt-get update && sudo apt-get install libsodium-dev;

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - cmake
    - protobuf-compiler 
    - libboost-dev 
    - libgoogle-glog-dev 
    - libgflags-dev
    - libprotobuf-dev 
    - libncurses5-dev 

branches:
  only:
    - master
      
script:
  - mkdir build
  - cd build
  - cmake ../ -DBUILD_TEST=1 && make

