language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - git submodule update --init --recursive
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      sudo apt-get install libboost-dev  
    fi

script: 
  - mkdir build
  - cd build
  - cmake ../ -DBUILD_TEST=1 && make
