os: linux
dist: xenial
sudo: required
language: cpp
compiler: gcc

before_install:
  - uname -a
  - git submodule update --init --recursive
  - sudo apt-get update -qq

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - protobuf-compiler
    - libsodium-dev
    - libgoogle-glog-dev
    - libgflags-dev
    - libprotobuf-dev

branches:
  only:
    - master

script:
  - mkdir build
  - cd build
  - cmake ../ -DBUILD_TEST=1 && make && ./test/EternalTCP-test
